"use client";
import { HiOutlineUserGroup } from "react-icons/hi";
import { FaRegUser } from "react-icons/fa";
export const CollectionData = [
  {
    id: 1,
    image: "../assest/education.jpg",
    heading: "Education",
    link_: "/collection/education",
  },
  {
    id: 2,
    image: "../assest/car-img.jpg",
    heading: "Game",
    link_: "/collection/games",
  },
  {
    id: 3,
    image: "../assest/hand-puzzle.jpg",
    heading: "Business",
    link_: "/collection/business",
  },
  {
    id: 4,
    image: "../assest/gramophone.webp",
    heading: "Entertainment",
    link_: "/collection/entertainment",
  },
  {
    id: 5,
    image: "../assest/earth-img.jpg",
    heading: "Plants",
    link_: "/collection/plants",
  },
  {
    id: 6,
    image: "../assest/piggy-bank.jpg",
    heading: "Finance",
    link_: "/collection/Finance",
  },
  {
    id: 7,
    image: "../assest/food.jpg",
    heading: "Food",
    link_: "/collection/food",
  },
  {
    id: 8,
    image: "../assest/play-girl.avif",
    heading: "Sports",
    link_: "/collection/sports",
  },
  {
    id: 9,
    image: "../assest/lifestyle.jpg",
    heading: "Lifestyle",
    link_: "/collection/Lifestyle",
  },
  {
    id: 10,
    image: "../assest/lifestyle.jpg",
    heading: "Lifestyle",
    link_: "/collection/Lifestyle",
  },
  {
    id: 11,
    image: "../assest/zoom_meeting.jpg",
    heading: "zoom meeting",
    link_: "/collection/zoom_meeting",
  },
  {
    id: 12,
    image: "../assest/lifestyle.jpg",
    heading: "Lifestyle",
    link_: "/collection/Lifestyle",
  },
];

export const FavoritesItem = [
  {
    image: "../assest/location-earth.jpg",
    name: "Titus Kitamura",
    heading: "Get Smarter with Products",
    time: "16 Qs",
    avtar: "../assest/image1.jpg",
    play: "5.6K plays",
    month: "2 months ago",
  },
  {
    image: "../assest/heart-shape.jpg",
    name: "Titus Kitamura",
    heading: "Great Idea Come from",
    time: "16 Qs",
    avtar: "../assest/image2.jpg",
    play: "5.6K plays",
    month: "2 months ago",
  },
  {
    image: "../assest/smile-emojis.jpg",
    name: "Titus Kitamura",
    heading: "Having Fun & Always from",
    time: "16 Qs",
    avtar: "../assest/image5.jpg",
    play: "5.6K plays",
    month: "2 months ago",
  },
  {
    image: "../assest/books_pen.jpg",
    name: "Titus Kitamura",
    heading: "Can you Imagine, world",
    time: "16 Qs",
    avtar: "../assest/image6.jpg",
    play: "5.6K plays",
    month: "2 months ago",
  },
  {
    image: "../assest/brain.webp",
    name: "Titus Kitamura",
    heading: "Get Smarter with Products",
    time: "16 Qs",
    avtar: "../assest/image1.jpg",
    play: "5.6K plays",
    month: "2 months ago",
  },
  {
    image: "../assest/smile-emojis.jpg",
    name: "Titus Kitamura",
    heading: "Great Idea Come from",
    time: "16 Qs",
    avtar: "../assest/image2.jpg",
    play: "5.6K plays",
    month: "2 months ago",
  },
  {
    image: "../assest/zoom_meeting.jpg",
    name: "Titus Kitamura",
    heading: "Having Fun & Always From",
    time: "16 Qs",
    avtar: "../assest/image5.jpg",
    play: "5.6K plays",
    month: "2 months ago",
  },
];

export const QuizzoItem = [
  {
    image: "../assest/poster-school.jpg",
    name: "Titus Kitamura",
    heading: "Get Smarter with Products",
    time: "16 Qs",
    avtar: "../assest/image1.jpg",
    play: "5.6K plays",
    public: "Public",
    publicIcon: <HiOutlineUserGroup />,
    month: "2 months ago",
  },
  {
    image: "../assest/idea-hand.jpg",
    name: "Titus Kitamura",
    heading: "Great Idea Come from",
    time: "16 Qs",
    avtar: "../assest/image2.jpg",
    play: "5.6K plays",
    publicIcon: <FaRegUser />,
    public: "Only Me",
    month: "2 months ago",
  },
  {
    image: "../assest/battle_hnd.webp",
    name: "Titus Kitamura",
    heading: "Having Fun & Always from",
    time: "16 Qs",
    avtar: "../assest/image5.jpg",
    play: "5.6K plays",
    publicIcon: <FaRegUser />,
    public: "Only Me",
    month: "2 months ago",
  },
  {
    image: "../assest/calendar.jpg",
    name: "Titus Kitamura",
    heading: "Can you Imagine, world",
    time: "16 Qs",
    avtar: "../assest/image6.jpg",
    play: "5.6K plays",
    public: "Public",
    publicIcon: <HiOutlineUserGroup />,
    month: "2 months ago",
  },
  {
    image: "../assest/calendar.jpg",
    name: "Titus Kitamura",
    heading: "Get Smarter with Products",
    time: "16 Qs",
    avtar: "../assest/image1.jpg",
    play: "5.6K plays",
    publicIcon: <FaRegUser />,
    public: "Only Me",
    month: "2 months ago",
  },
  {
    image: "../assest/battle_hnd.webp",
    name: "Titus Kitamura",
    heading: "Great Idea Come from",
    time: "16 Qs",
    avtar: "../assest/image2.jpg",
    play: "5.6K plays",
    public: "Public",
    publicIcon: <HiOutlineUserGroup />,
    month: "2 months ago",
  },
  {
    image: "../assest/calendar.jpg",
    name: "Titus Kitamura",
    heading: "Having Fun & Always From",
    time: "16 Qs",
    avtar: "../assest/image5.jpg",
    play: "5.6K plays",
    publicIcon: <FaRegUser />,
    public: "Only Me",
    month: "2 months ago",
  },
];
